FROM rocm/pytorch-training:v25.4

# Set working directory
WORKDIR /home/hotaisle/docker_training

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV HF_HUB_ENABLE_HF_TRANSFER=1
ENV PYTORCH_ROCM_ARCH="gfx942"
ENV MAX_JOBS=104

# Install required dependencies
RUN apt update && apt install -y libstdc++-12-dev && \
    pip install --upgrade numba scipy huggingface-hub[cli,hf_transfer] setuptools_scm && \
    pip install amdsmi "numpy<2"

# Clone and install ms-swift
RUN git clone https://github.com/modelscope/ms-swift.git && \
    cd ms-swift && pip install -e . && pip install setuptools -U && cd ..

# Clone and install vllm
RUN git clone https://github.com/ROCm/vllm.git && \
    cd vllm && \
    pip install -r requirements/rocm.txt && \
    python3 setup.py develop && \
    cd ..


RUN pip install git+https://github.com/huggingface/trl.git && \
    pip install math-verify==0.5.2 hf_transfer wandb && \
    pip install --upgrade pillow


RUN apt install unzip -y && \
    wget -O quark.zip https://www.xilinx.com/bin/public/openDownload?filename=quark-0.6.0.zip && \
    unzip quark.zip && \
    cd quark-0.6.0+dba9ca364 && pip install quark-0.6.0+dba9ca364-py3-none-any.whl

RUN  huggingface-cli login --token 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 && \
    wandb login e2ed6858c3226f51a97cdffcb81282ee2164bcec